name: "Deploy Pipeline"
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy Docker compose
        run: |
         docker compose up -d --remove-optional

         docker image prune -f
